# Generated by Django 4.2.7 on 2023-12-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_alter_course_slug_alter_form_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
