# Generated by Django 4.2.7 on 2023-12-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0004_alter_form_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='material',
        ),
        migrations.RemoveField(
            model_name='form',
            name='slug',
        ),
        migrations.AddField(
            model_name='form',
            name='material_provided',
            field=models.CharField(choices=[('notebook', 'Notebook'), ('pen', 'Pen'), ('exam_paper', 'Exam Paper')], default='notebook', max_length=20),
        ),
        migrations.AlterField(
            model_name='form',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='form',
            name='purpose',
            field=models.CharField(choices=[('enquiry', 'For Enquiry'), ('order', 'Place Order'), ('return', 'Return')], max_length=10),
        ),
    ]
