# Generated by Django 4.2.7 on 2023-12-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0006_alter_form_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='form',
            name='material_provided',
        ),
        migrations.AddField(
            model_name='form',
            name='material_provided',
            field=models.ManyToManyField(to='storeapp.material'),
        ),
    ]
